# Generated by Django 4.2.16 on 2024-11-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('kingdom', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
