# Generated by Django 4.2.16 on 2024-11-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0002_birds_slug_alter_birds_image_alter_birds_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
