# Generated by Django 4.2.16 on 2024-11-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0003_alter_birds_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birds',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
