# Generated by Django 4.2.16 on 2024-11-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdapp', '0004_alter_birds_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Birds',
        ),
    ]
