# Generated by Django 4.2.16 on 2024-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('birdapp', '0005_delete_birds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('domain', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', max_length=250)),
                ('kingdom', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
